basepath: './data'
pretrained: './weights/weightsmatching_net_0_3000.pth'
epochs: 20
alpha_aux: 1.0
alpha_ds: 0.2
alpha_ap: 1
ssim_alpha: 0.9
alpha_lr: 0.1
alpha_aux: 20
ssim_windom: 5
lambda_c: 10
lambda_a: 1
lambda_d: 1
lambda_r: 5
lambda_i: 0
warmup: True
stereo: False
auxilary: False
weights_dir: './weights'
summary_root: './summary'
tensorboard_val_freq: 10000 #(after every 10000 iterations do validation)
weights_freq: 1000 #(save weights after every 1000 iterations)
resize: 1
crop_size: [420,580]
batch_size: 2
device_ids: [0]
val_precent: 0.05
image_on_tensorboard: 100 # number of validation steps after which to write images on tensorboard
val_percent: 0.05 #percent of data in validation
multiscale_disp_weights: [1.0,0.9,0.7,0.5]
