basepath: './data'
gan_pretrained: './weights/'
pretrained_epoch: 'latest'
stm_pretrained: True
epochs: 20
alpha_ds: 100.0
alpha_ap: 1.0
alpha_ssim: 0.9
alpha_lr: 2.0
alpha_aux: 20
ssim_windom: 5
lambda_c: 10
lambda_a: 1
lambda_d: 1
lambda_r: 5
warmup: False
weights_dir: './weights'
summary_root: './summary'
weights_freq: 1000 #(save weights after every 1000 iterations)
resize: 1
crop_size: [420,580]
batch_size: 2
device_ids: [0,1]
val_precent: 0.05
image_on_tensorboard: 100 # number of validation steps after which to write images on tensorboard
multiscale_disp_weights: [1.0,0.5,0.25,0.125]
